spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inc
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:      ddl-auto: update  
  mvc:    pathmatch:      matching-strategy: ant-path-matcher    
server:  port: 9000    